version: "3.9"
services:
  notes-api-service:
    build: ./notes-api-service
    container_name: notes-api-service
    depends_on:
      - "mongo"
    ports:
      - "12345:12345"
    environment:
      MONGO_URI: mongodb://mongo:27017
      LOGINSERVICE_APP_JWTSECRET: thiskeyisnotusedforproductiononlyfordevelopmentpurposes
      CORS_ORIGIN: http://localhost:3000
  login-service:
    build: ./login-service
    container_name: login-service
    depends_on:
      - "mongo"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      LOGINSERVICE_APP_JWTSECRET: thiskeyisnotusedforproductiononlyfordevelopmentpurposes
      LOGINSERVICE_APP_CORSORIGIN: http://localhost:3000
  # MongoDB
  mongo:
    image: "mongo:4.2.6-bionic"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db
    restart: always
  # Mongo Express Web-based MongoDB admin interface
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - "mongo"
    ports:
      - "8081:8081"
    restart: always
