name: frontend-ci
          
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: eliasfrykholm/keep-frontend
          registry: docker.io
          dockerfile: notes-frontend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
