name: terraform-apply
          
on:
  push:
    branches: [ master ]


jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCES_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_mongo_initdb_root_username: ${{ secrets.MONGO_INITDB_ROOT_USERNAME}}
          TF_VAR_mongo_initdb_root_password: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD}}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET}}
          TF_VAR_registry_username: ${{ github.actor }}
          TF_VAR_registry_password: ${{ secrets.GITHUB_TOKEN }}
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform validation
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCES_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_mongo_initdb_root_username: ${{ secrets.MONGO_INITDB_ROOT_USERNAME}}
          TF_VAR_mongo_initdb_root_password: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD}}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET}}
          TF_VAR_registry_username: ${{ github.actor }}
          TF_VAR_registry_password: ${{ secrets.GITHUB_TOKEN }}
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform